language: php
php:
    - '7.1'
    - '7.2'
    - '7.3'
    - '7.4snapshot'
    - 'nightly'
install:
    composer install

script:
    - ./vendor/bin/phpunit --testdox --coverage-clover=coverage/report/coverage.xml
    - ./vendor/bin/phpcs
    - ./vendor/bin/psalm

after_success:
    - bash <(curl -s https://codecov.io/bash)
